# Generated by Django 5.0.2 on 2024-02-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Admin", "0004_remove_condidat_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recruteur",
            fields=[
                ("id_recruteur", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("login", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("entreprise", models.CharField(max_length=255)),
                ("num_patent", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "clef_recruteur",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
