# Generated by Django 5.0.2 on 2024-02-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=255)),
                ('nom', models.TextField(max_length=100)),
                ('prenom', models.TextField(max_length=100)),
                ('tel', models.TextField(max_length=10)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recruteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=255)),
                ('nom', models.TextField(max_length=100)),
                ('prenom', models.TextField(max_length=100)),
                ('telephone', models.TextField(max_length=15)),
                ('entreprise', models.TextField(max_length=100)),
                ('numero_patent', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
    ]
